### ISSUE TITLE
Reduce CPU usage

### ISSUE THREAD

**Issue by ovz** [hatnote/listen-to-wikipedia#18]
Great project! Cannot listen to it in the background though because my 2011 MacBook Pro starts rotating CPU fans and it gets too loud. Could you please consider what can be done to reduce CPU consumption?

**Comment by mahmoud** [comment]
Thanks! I'll add a "background mode" setting that disables the CPU-intensive parts of the site. Could you let me know what browser you're using (and version of Mac OS X, ideally)?

It's funny, L2W was written on 2011-era computers in 2013, and now it's 2015, you'd expect Moore's Law to do us some favors, but I guess it's Murphy's Law all the way down ;)

**Comment by ovz** [comment]
Sure. The browser is
Version 43.0.2357.81 (64-bit) Google Chrome is up to date. And the machine's  OS X 10.9.5 2.2GHz Intel Core i7 8Gb 1333MHz DD3. 
Yeah, funny enough. They are giving us more cores but not too many. I/O speeds (USB3) and Battery life does get better. 

WBR Oleg Zhylin ovz@yahoo.com 


     On Wednesday, June 3, 2015 1:02 PM, Mahmoud Hashemi <notifications@github.com> wrote:
   

 Thanks! I'll add a "background mode" setting that disables the CPU-intensive parts of the site. Could you let me know what browser you're using (and version of Mac OS X, ideally)?It's funny, L2W was written on 2011-era computers in 2013, and now it's 2015, you'd expect Moore's Law to do us some favors, but I guess it's Murphy's Law all the way down ;)—

**Comment by mahmoud** [comment]
Hey ovz, I pushed a change to the site last night, "Hide graphics for background listening". Just refresh the page and you'll see it. It seems to bring down CPU usage by ~60% :)

 Feel free to let me know here if it's not working for you.

**Comment by ovz** [comment]
Works great! Thanks.  WBR Oleg Zhylin ovz@yahoo.com 


     On Thursday, June 4, 2015 2:29 PM, Mahmoud Hashemi <notifications@github.com> wrote:
   

 Hey ovz, I pushed a change to the site last night, "Hide graphics for background listening". Just refresh the page and you'll see it. It seems to bring down CPU usage by ~60% :)Feel free to let me know here if it's not working for you. —
