### ISSUE TITLE
Add the Esperanto Wikipedia

### ISSUE THREAD

**Issue by capiscuas** [hatnote/listen-to-wikipedia#20]
Hi! Could you please add the Esperanto Wikipedia to your tool? I would really appreciate it. Thanks a lot!

The tool is great.

**Comment by pizzamaker** [comment]
Came in here to ask for this as well :)

Either that or a mechanism to allow listening to any Wikipedia.

**Comment by mahmoud** [comment]
I've added Esperanto to the list, though with some days having <500 edits, you may have to start writing to hear it. :) Have fun!

**Comment by capiscuas** [comment]
Thanks a lot! This will motivate more edits for sure.
Dankon!

**Comment by pizzamaker** [comment]
Are you positive it's working? I hear nothing, and refreshing the recent changes page I can see there has been edits, but hatnote is not picking them up for some reason.

**Comment by mahmoud** [comment]
Yes, L2W only shows mainspace edits. Perhaps for lower-traffic wikis we can add a toggle, as any activity is interesting activity for dedicated editors/listeners :)  

Also, this wikimon test client does not filter the activity and might be useful: http://alpha.hatnote.com/wikimon-test/index.html

Esperanto is on port 9360 (use `ws://alpha.hatnote.com:9360` for the URL)

**Comment by pizzamaker** [comment]
I agree with this idea of adding a toggle. You know, L2W can be seen as a cute project, but it's pretty useful for keeping track of low-traffic Wikipedias. Certainly better than constantly refreshing the recent changes, anyway.

**Comment by mahmoud** [comment]
That's what I've been saying for years! Yeah, @slaporte and I will get on that. If you'd like, you can create an issue :)
